env:
  CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy Chocolatey Package for taskurai
    runs-on: windows-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2    
      - name: Push Choco
        shell: powershell
        run: |         
          $version = (Invoke-WebRequest -Uri 'https://get.taskurai.com/releases/latestversion.txt').Content.Trim()
          echo "Version: " + $version
          
          $url = "https://get.taskurai.com/releases/${version}/taskurai_${version}_win-x64.zip"
          $output = "taskurai_" + ${version} + "_win-x64.zip"
          
          echo "Url: " + $url
          echo "Output: " + $output

          Set-Location -Path .\taskurai\
          (Get-Content '.\taskurai.nuspec' -Raw).Replace("<version>X.X.X</version>", "<version>" + ${version} + "</version>") | Out-File '.\taskurai.nuspec'

          Set-Location -Path .\tools
          Invoke-WebRequest -Uri $url -OutFile $output
          $checksum = Get-FileHash -Path $output
          $hash = $checksum.Hash
          (Get-Content '.\chocolateyinstall.ps1' -Raw).Replace("X.X.X",  ${version} ).Replace("XXXXXX", "${hash}") | Out-File '.\chocolateyinstall.ps1'

          Set-Location -Path ..\legal
          (Get-Content '.\VERIFICATION.txt') | Foreach-Object {
              $_ -replace 'XXXXXX', "${hash}" `
                -replace 'X.X.X', ${version}
              } | Set-Content '.\VERIFICATION.txt'
          $licenseFileUrl = "https://github.com/taskurai/taskurai-chocolatey/blob/main/LICENSE"
          $licenseFileOutput = "LICENSE.txt"
          Invoke-WebRequest -Uri $licenseFileUrl -OutFile $licenseFileOutput

          Set-Location -Path ..\
          Choco Pack

          choco push -k $env:CHOCO_API_KEY -s https://push.chocolatey.org/
